### ISSUE TITLE
Wallet crashes while send LP Token

### ISSUE THREAD

**Issue by bernd2022** [BirthdayResearch/defichain-electrum#6]
Try to receive and send a LP Token, e.g. DUSD-DFI
Receiving the LP Token works fine.

Sending the LP Token crashes the electrum wallet.

Last entry in the log:
20220502T170829.094141Z |    ERROR | asyncio | Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/tmp/.mount_defichV3VN2v/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <Context object at 0x7faefd4f7550> is already entered

**Comment by bernd2022** [comment]
**Catched a detailed Traceback:**

Traceback (most recent call last):
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/main_window.py", line 1734, in do_pay
    self.do_pay_invoice(self.pending_invoice)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/main_window.py", line 1748, in do_pay_invoice
    self.pay_onchain_dialog(self.get_coins(), invoice.outputs)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/main_window.py", line 1801, in pay_onchain_dialog
    conf_dlg = ConfirmTxDialog(window=self, make_tx=make_tx, output_value=output_value, is_sweep=is_sweep)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/confirm_tx_dialog.py", line 177, in __init__
    BlockingWaitingDialog(window, _("Preparing transaction..."), self.update_tx)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/util.py", line 344, in __init__
    task()
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/confirm_tx_dialog.py", line 86, in update_tx
    self.tx = self.make_tx(fee_estimator)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/gui/qt/main_window.py", line 1794, in <lambda>
    is_sweep=is_sweep)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/wallet.py", line 1364, in make_unsigned_transaction
    base_tx = self.get_unconfirmed_base_tx_for_batching()
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/wallet.py", line 1225, in get_unconfirmed_base_tx_for_batching
    for hist_item in self.get_history():
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/util.py", line 1114, in func_wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/address_synchronizer.py", line 103, in func_wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/address_synchronizer.py", line 483, in f
    return func(self, *args, **kwargs)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/address_synchronizer.py", line 512, in get_history
    c, u, x = self.get_balance(domain)
  File "/tmp/.mount_defichkxMWK8/usr/lib/python3.7/site-packages/electrum/address_synchronizer.py", line 943, in get_balance
    cc += c
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
 
Additional information
Electrum version: 4.1.5 
Python version: 3.7.10 (default, Jun 28 2018, 19:01:02) [GCC 5.4.0 20160609] 
Operating system: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid 
Wallet type: 2of2 
Locale: en_US
